spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://101.79.9.79/gonggansongil
    username: root
    password: rlatpdud13795@
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


app:
  file:
    saveDir: D:\\workspace\\gongson\\g_back_files