spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://101.79.9.79/gonggansongil
    username: root
    password: rlatpdud13795@
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

ncloud:
  cdnUrl: http://gongson.cdn.ntruss.com/interiorTip/
  accessKey: ncp_iam_BPAMKR3ub86D5JAEi7QK
  secretKey: ncp_iam_BPKMKRElGQSBVeRROCwFTtbIlEz4oQal4w

app:
  file:
    saveDir: D:\\gongson\\uploads\\